- report-service/sql-script/elr_fhir.sql
- report-service/sql-script/elr_validated.sql
- report-service/src/main/java/gov/cdc/dataingestion/conversion/integration/HL7ToFHIRConversion.java
- report-service/src/main/java/gov/cdc/dataingestion/conversion/integration/interfaces/IHL7ToFHIRConversion.java
- report-service/src/main/java/gov/cdc/dataingestion/conversion/repository/IHL7ToFHIRRepository.java
- report-service/src/main/java/gov/cdc/dataingestion/conversion/repository/model/HL7ToFHIRModel.java
- report-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java
- report-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaProducerService.java
- report-service/src/main/java/gov/cdc/dataingestion/validation/repository/model/ValidatedELRModel.java
This story is to save the FHIR (converted from HL7) to SQL Server Database. The HL7 record is validated and converted to FHIR document in the previous stories worked by Duc and this is the continuation of that.
Also, created a SQL script to create the required table in the database. Updated the ``elr_validated`` SQL script to reference the raw_id as Foreign Key.
Created a Repository Interface to save the document from the Kafka Consumer Class and updated the model class to reflect the changes made.
https://cdc-nbs.atlassian.net/browse/CNDIT-229
I and Duc tested the changes in his local workspace and was able to see the data being saved in the ``elr_fhir`` table in ``NBS_DataIngest`` Database in the AWS RDS Instance.
> CNDIT-229 - Save FHIR Document to Database

- report-service/sql-script/elr_validated.sql
- report-service/src/main/java/gov/cdc/dataingestion/exception/DuplicateHL7FileFoundException.java
- report-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java
- report-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaProducerService.java
- report-service/src/main/java/gov/cdc/dataingestion/validation/integration/validator/HL7DuplicateValidator.java
- report-service/src/main/java/gov/cdc/dataingestion/validation/integration/validator/interfaces/IHL7DuplicateValidator.java
- report-service/src/main/java/gov/cdc/dataingestion/validation/repository/IValidatedELRRepository.java
- report-service/src/main/java/gov/cdc/dataingestion/validation/repository/model/ValidatedELRModel.java
- report-service/src/main/resources/application.yaml
- report-service/src/test/java/gov/cdc/dataingestion/report/controller/ReportControllerTests.java
- report-service/src/test/java/gov/cdc/dataingestion/validation/integration/validator/HL7DuplicateValidatorTest.java
This PR is the first baby step for the deduplication algorithm which we planned to implement in the Data Ingestion pipeline. With this change, after validating the incoming HL7 document, 32 byte hash for the document is generated and validated against the database for any existing duplicate records. If none present, then validation check passes and the document is converted to FHIR. If the validation fails, then an exception is thrown and the record is moved to the ``elr_validated-dlt`` kafka topic.
- https://cdc-nbs.atlassian.net/browse/CNDIT-232
- Unit tests created and see the coverage results below.
- I was able to test the changes in the local database and hit the endpoint using the test payload. Successful payloads were inserted into raw, validated and fhir tables. Unsuccessful ones …
> [CNDIT-232] Deduplication algorithm to check HL7 duplicate

- report-service/build.gradle
- report-service/src/main/java/gov/cdc/dataingestion/deadletter/model/ElrDeadLetterDto.java
- report-service/src/main/java/gov/cdc/dataingestion/nbs/converters/Hl7ToRhapsodysXmlConverter.java
- report-service/src/test/java/gov/cdc/dataingestion/kafka/service/KafkaConsumerServiceTest.java
- report-service/src/test/java/gov/cdc/dataingestion/nbs/converter/Hl7ToRhapsodysXmlConverterTest.java
CNDIT-496's issues:
- Xml pipeline failed and threw message into dlt in this scenario
- Message contain date time with time zone such as "20230101125901-0700". Initially, we didn't handle this properly and it caused the parsing exception
- Second issue in the xml pipeline is a null exception at OBR type. Added null check
Unit test result
> Fix bug where XML pipeline threw parsing exception on specific scenario

- data-ingestion-service/src/main/java/gov/cdc/dataingestion/config/KafkaConsumerConfig.java
- data-ingestion-service/src/main/java/gov/cdc/dataingestion/exception/DiAsyncException.java
- data-ingestion-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java
- data-ingestion-service/src/test/java/gov/cdc/dataingestion/kafka/service/KafkaConsumerServiceTest.java
- data-ingestion-service/src/test/load-testing/py_generate_msg.py
- data-ingestion-service/src/test/load-testing/request_di.sh
**Error:** 
- indefinite loop occurred within xml-transformation logic
**Method info:** 
- prior to this pr, the method is executed synchronously as follow converting data to xml (intensive process) -> persist data to nbs -> trigger producer -> persist data to di.
**Scenario and issue:** 
- When making like 1 to 10 requests subsequently, things will work normally. However, when we dump like 100 or 1000 requests, xml transformation logic broke the pipeline and causing the pipeline to be executed in the loop.
- Due to the synchronous nature and under the heavy load, it seems to cause kafka consumer to be in the strange state such as consumer rebalancing (leading to duplicate processing of msg), consumer lagging (msg taking longer to process)
**Update:**
- Introduced asynchronous process for …
> Cndit 853 - fixing error where xml pipeline is being executed in the loop

- data-ingestion-service/src/main/java/gov/cdc/dataingestion/rawmessage/controller/ElrReportsController.java
- data-ingestion-service/src/test/java/gov/cdc/dataingestion/rawmessage/ElrReportsControllerTest.java
Remove HL7 validation header as this is redundant, validator will be on by default for injection and re-injection endpoint
> set validation to true by default, no more header

- data-ingestion-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java
- data-ingestion-service/src/main/java/gov/cdc/dataingestion/share/helper/TimeStampHelper.java
Fix for Elr_raw and Elr_dlt showing different timestamps. 
It worked correctly when we posted the record from the cloud, but local time was added in the DB if the record was from the local DI service.
> Fix for Elr_raw and Elr_dlt showing different timestamps

- data-ingestion-service/src/main/java/gov/cdc/dataingestion/camel/routes/ElrProcessStatusComponent.java
- data-ingestion-service/src/main/java/gov/cdc/dataingestion/reportstatus/model/EdxActivityLogStatus.java
- data-ingestion-service/src/main/java/gov/cdc/dataingestion/reportstatus/service/ReportStatusService.java
- data-ingestion-service/src/test/java/gov/cdc/dataingestion/camel/routes/ElrProcessStatusComponentTest.java
Removed 'record id' from the status info endpoint and sftp status.
> To remove record id from the Activity Logs display

- .gitignore
- .vscode/settings.json
- deduplication/db/Dockerfile
- deduplication/db/initialize/initialize.sh
- deduplication/db/initialize/restore.d/00-initial.sql
- deduplication/db/initialize/restore.d/README.md
- docker-compose.yml
Adds a `deduplication` directory to contain service(s), development database, and other items relevant to patient deduplication.
Database image requires a `DEDUPLICATION_DATABASE_PASSWORD` environment variable be set. It is recommended for developers to create a `.env` file with the desired password.
```bash
DEDUPLICATION_DATABASE_PASSWORD=fake.fake.fake.1234
```
- **Related story**: [CND-146](https://cdc-nbs.atlassian.net/browse/CND-146)
[CND-146]: https://cdc-nbs.atlassian.net/browse/CND-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add deduplication folder with database container"

- cdaschema/build.gradle
- data-ingestion-service/build.gradle
- hl7-parser/build.gradle
Fixes the gradle build to work locally when data-ingestion `/libs` is not already present, and hopefully fixes the docker container build.
Last action to fail: https://github.com/CDCgov/NEDSS-DataIngestion/actions/runs/12302291088
Build order (note `:cdaschema:copyJar NO-SOURCE`)
1. The `cdaschema.jar` was failing to copy.
2. The gradle script was complaining about a dependency not being listed
Working local `./gradlew data-ingestion-service:buildNeeded -x test`
> Fix build 🤞

- cdaschema/build.gradle
- data-ingestion-service/build.gradle
Attempt 2 at fixing the build failure for data-ingestion-service container.  Was able to reproduce github action build failure by fully cleaning local environment prior to build.
Completely cleaned local env and was able to successfully build using: 
```
rm -rf data-ingestion-service/libs && ./gradlew clean && ./gradlew :data-ingestion-service:buildNeeded -x test --no-daemon
```
Was able to build local docker container successfully using:
```
docker compose up data-ingestion-service --build
```
> Build test

- docker-compose.yml
- docs/DevSetup.md
- srte-data-service/Dockerfile
Adds a docker compose entry for the `srte-data-service` that is configured to use local `di-mssql` and `di-keycloak` containers as dependencies.
> Local development: `srte-data-service` docker container

- data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/person/PatientMatchingService.java
- data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/person/matching/DeduplicationClient.java
- data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/person/matching/DeduplicationService.java
- data-processing-service/src/test/java/gov/cdc/dataprocessing/service/implementation/person/PatientMatchingServiceTest.java
- data-processing-service/src/test/java/gov/cdc/dataprocessing/service/implementation/person/matching/DeduplicationClientTest.java
If `features.modernizedMatching.enabled` is `false`, no DeduplicationService or RestClient bean will be created. Causing a failure in the dependency injection.
This PR resolves this failure due to missing bean by using `ObjectProvider`.
> Use ObjectProvider for service dependency

- srte-data-service/build.gradle
- srte-data-service/src/test/java/gov/cdc/srtedataservice/SrteDataServiceApplicationTests.java
- srte-data-service/src/test/java/gov/cdc/srtedataservice/containers/MsSqlContainerInitializer.java
- srte-data-service/src/test/java/gov/cdc/srtedataservice/containers/NbsDatabaseContainer.java
- srte-data-service/src/test/java/gov/cdc/srtedataservice/containers/UseNbsDatabaseContainer.java
- srte-data-service/src/test/resources/application-test.yaml
1. Updates the spring boot dependencies for the `srte-data-service`
| Dependency | Previous version | New version |
| --- | --- |--- |
|spring-boot-starter-web | 3.4.0 | 3.4.1|
|spring-boot-starter-oauth2-resource-server | 3.4.0 | 3.4.1|
|spring-boot-starter-data-jpa | 3.4.0 | 3.4.1|
2. Adds test containers to `srte-data-service` to allow database connection
- None -
> Security findings 3

- .github/workflows/Build-and-deploy-data-ingestion-and-processing.yaml
- .github/workflows/sonar.yaml
Attempts to resolve test failures caused by invalid database credentials when triggering `sonar.yaml` from the `Build-and-deploy-data-ingestion-and-processing.yaml` workflow.
1. Pass secrets to sonar workflow call
2. Set database secrets as required in sonar workflow call.
I am not good at testing workflows prior to merging them in. Cannot guarantee this will fix.
> Pass database credentials to sonar run for build-and-deploy

- deduplication/src/main/java/gov/cdc/nbs/deduplication/DeduplicationApplication.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/BatchJobConfig.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/BatchJobScheduler.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/TestController.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/model/LinkResult.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/model/MatchCandidate.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/model/MatchRequest.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/model/MatchResponse.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/service/DuplicateCheckService.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/service/PatientRecordService.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/step/DuplicatesProcessor.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/step/MatchCandidateWriter.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/step/UnprocessedPersonReader.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/seed/JobConfig.java
- deduplication/src/main/resources/application.yaml
- deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/BatchJobConfigTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/BatchJobSchedulerTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/TestControllerTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/service/DuplicateCheckServiceTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/service/PatientRecordServiceTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/step/DuplicatesProcessorTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/step/MatchCandidateWriterTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/step/UnprocessedPersonReaderTest.java
Implemented batch job for deduplication processing. The job reads unprocessed patient records, processes them to identify potential duplicates, and writes match candidates
https://cdc-nbs.atlassian.net/browse/CND-163
> Adding batch job for De-duplication.

- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/AlgorithmController.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/AlgorithmService.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/dto/Pass.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/mapper/AlgorithmConfigMapper.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/mapper/AlgorithmRequestMapper.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/model/MatchingConfigRequest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/AlgorithmControllerTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/AlgorithmServiceTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/dto/PassTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/mapper/AlgorithmConfigMapperTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/mapper/AlgorithmRequestMapperTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/model/MatchingConfigRequestTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/model/MatchingConfigurationTest.java
When no configuration has been saved, the NBS configuration API returns null. The configuration should default to the dibbs_enhanced algorithm provided by the Record Linker team. The MPI database to be queried for the GET request, translating the DIBBS algorithm json into the object expected by the UI.
On a fresh setup of the Modernized NBS deduplication services, a default Record Linkage algorithm is available
The default algorithm is the dibbs_enhanced algorithm
The GET algorithm API does not return null prior to an algorithm being saved
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CND-193?atlOrigin=eyJpIjoiOWVlNmYyOGFiMDRiNGEzODhhZDkyMGVhNzBkZDdmNjQiLCJwIjoiaiJ9)
> CND-193-Default-DIBBS-Configuration-Initial-State

- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/AlgorithmController.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/AlgorithmControllerTest.java
When managing the Record Linker algorithm configuration, STLTs are expected to test the algorithm in a dev or test environment. Once the algorithm is finalized, the configuration will need to be migrated to the production environment.
Providing simple APIs for importing and exporting the configuration will ease this process.
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CND-195)
> cnd-195-import api and unit test

- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/AlgorithmController.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/AlgorithmControllerTest.java
When managing the Record Linker algorithm configuration, STLTs are expected to test the algorithm in a dev or test environment. Once the algorithm is finalized, the configuration will need to be migrated to the production environment.
Providing simple APIs for importing and exporting the configuration will ease this process.
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CND-194?atlOrigin=eyJpIjoiYWJlZjk3YTUyN2YyNDBlODljY2FhZjgzNjc0NDU1MDYiLCJwIjoiaiJ9)
> CND-194 export api and unit test

- containers/record-linker/Dockerfile
- deduplication/src/main/resources/application.yaml
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/AlgorithmServiceTest.java
- docker-compose.yml
1. Updates record linker container to latest:  v25.2.0
2. Updates port for RL container to be `8062` to not conflict with modernization-api
3. Fixes a few warnings in a test
- **Related story**: [CND-224](https://cdc-nbs.atlassian.net/browse/CND-224)
[CND-224]: https://cdc-nbs.atlassian.net/browse/CND-224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update record linker 25.2.0

- data-processing-service/src/main/resources/application.yaml
- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/AlgorithmService.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/dto/AlgorithmPass.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/dto/Kwargs.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/dto/Pass.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/mapper/AlgorithmConfigMapper.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/mapper/AlgorithmRequestMapper.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/AlgorithmControllerTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/AlgorithmServiceTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/dto/KwargsTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/dto/PassTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/mapper/AlgorithmConfigMapperTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/mapper/AlgorithmRequestMapperTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/model/MatchingConfigRequestTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/model/MatchingConfigurationTest.java
As a user, I want the 'Export/Import Configuration' feature to include data elements so that when I export a configuration, all relevant data elements are included, and when I import a configuration, the data elements are restored along with the pass configuration.
1. The existing API must be updated to support exporting and importing data elements along with the pass configuration.
2. The exported data elements should also contain the odds ratio and the threshold.
3. The export file format should be application/json.
Export API response:
Import API body and Response:
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CND-227?atlOrigin=eyJpIjoiNWRiN2Y5YTg3MWM5NGFlYTg3MTUxZDEzNjViMDUxYzciLCJwIjoiaiJ9)
> CND-227: Export/Import Configuration with Data Elements

- data-ingestion-service/Dockerfile
> Vulnerability Scan: try fixing base image vulnerability

- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/AlgorithmController.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/dataelements/DataElementsController.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/pass/PassController.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/controller/MergeGroupController.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/controller/TestController.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/matching/MatchController.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/seed/SeedController.java
- deduplication/src/main/resources/application.yaml
- deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/controller/MergeGroupControllerTest.java
Updates the base path for the deduplication service to prevent conflict in a deployed environment.
New deduplication base: `/nbs/api/deduplication`
- **Related story**: [CND-234](https://cdc-nbs.atlassian.net/browse/CND-234)
[CND-234]: https://cdc-nbs.atlassian.net/browse/CND-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update base path to /nbs/api/deduplication. Remove /api from controllers

- containers/db/initialize/restore.d/04-create-deduplication-db.sql
- deduplication/src/main/java/gov/cdc/nbs/deduplication/health/HealthController.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/health/HealthResponse.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/health/HealthControllerTest.java
Adds a `/health` endpoint for deduplication API.
Removes extra `;` from init script
> Add health endpoint. Remove unnecessary semicolon

- data-ingestion-service/build.gradle
- data-ingestion-service/src/main/java/gov/cdc/dataingestion/security/config/SecurityConfig.java
- data-ingestion-service/src/main/resources/application.yaml
- srte-data-service/build.gradle
- srte-data-service/src/main/java/gov/cdc/srtedataservice/security/SecurityConfig.java
- srte-data-service/src/main/resources/application.yaml
This PR contains the addition of the new endpoint that will help the users to check for the health and status of the Data Ingestion service.
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2429)
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2431)
> [CNDE-2429] Added healthchecks for DI and SRTE services

- deduplication/src/main/java/gov/cdc/nbs/deduplication/constants/QueryConstants.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/controller/PatientMergeController.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/model/MatchesRequireReviewResponse.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/service/MergeGroupHandler.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/controller/PatientMergeControllerTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/service/MergeGroupHandlerTest.java
1. Updates response from merge list API to include paging information
2. Updates merge controller to have base path of `/merge`
- **Related story**: [CND-242](https://cdc-nbs.atlassian.net/browse/CND-242)
[CND-242]: https://cdc-nbs.atlassian.net/browse/CND-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Support paging of merge candidate list

- containers/db/initialize/restore.d/04-create-deduplication-db.sql
- deduplication/src/main/java/gov/cdc/nbs/deduplication/batch/mapper/PersonMergeDataMapper.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/batch/model/MatchesRequireReviewResponse.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/batch/model/PersonMergeData.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/batch/service/PatientRecordService.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/batch/step/MatchCandidateWriter.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/constants/QueryConstants.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/matching/MatchService.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/MatchesRequiringReviewResolver.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/MergeGroupHandler.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/PatientMergeController.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/PdfBuilder.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/model/PatientNameAndTime.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/batch/service/MergeGroupHandlerTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/batch/service/PatientRecordServiceTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/batch/step/MatchCandidateWriterTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/matching/MatchServiceTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/MatchesRequiringReviewResolverTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/PatientMergeControllerTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/PdfBuilderTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/sync/service/PersonInsertSyncHandlerTest.java
1. Adds person_local_id to `matches_requiring_review` table
2. Adds person local id lookup to patient name and add time lookup during the batch job processing
3. Moves some queries out of QueryConstants to better isolate usage
4. Changes merge APIs to use `matchId` instead of person_uid. This prevents any issue if the same patient is in multiple match groups
5. Return `matchId`, `personLocalId`, person `add_time` for use in the UI
- **Related story**: [CND-346](https://cdc-nbs.atlassian.net/browse/CND-346)
[CND-346]: https://cdc-nbs.atlassian.net/browse/CND-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cnd 346 patient local

- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonNamesMergeHandler.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/handler/PersonNamesMergeHandlerTest.java
Updates the `person_name` table to reassign selected names to the surviving patient
1- Names selected in the Surviving patient are not modified
2- Names de-selected in the Surviving patient are marked as INACTIVE
3- Names selected in Superseded patients have the person_name entries person_uid updated to the Surviving patient’s person_uid
4- Names de-selected in Superseded patients are not modified
https://cdc-nbs.atlassian.net/browse/CND-338
> Implement merging of selected person names

- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonAddressMergeHandler.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonNamesMergeHandler.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonPhoneEmailMergeHandler.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/handler/PersonAddressMergeHandlerTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/handler/PersonNamesMergeHandlerTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/handler/PersonPhoneEmailMergeHandlerTest.java
Implement phone & emai merge logic for patient merge API
1- Phone / Emails selected in the Surviving patient are not modified
2- Phone / Emails de-selected in the Surviving patient are marked as INACTIVE or LOG_DEL whichever is standard
3- Phone / Emails selected in Superseded patients have the entity_locator_participation entries entity_uid updated to the Surviving patient’s person_uid
4- Phone / Emails de-selected in Superseded patients are not modified
https://cdc-nbs.atlassian.net/browse/CND-340
> Implement phone & emai merge logic for patient merge API

- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonIdentificationsMergeHandler.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/handler/PersonIdentificationsMergeHandlerTest.java
Implement Identification record merge into surviving patient:
1-Identifications selected in the Surviving patient are not modified
2-Identifications de-selected in the Surviving patient are marked as INACTIVE or LOG_DEL whichever is standard
3-Identifications selected in Superseded patients are copied into new records on the Surviving patient
4-Identifications de-selected in Superseded patients are not modified
https://cdc-nbs.atlassian.net/browse/CND-341
> Implement Identification record merge into surviving patient

- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonEthnicityMergeHandler.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/model/PatientMergeRequest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/handler/AdminCommentMergeHandlerTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/handler/PersonAddressMergeHandlerTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/handler/PersonEthnicityMergeHandlerTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/handler/PersonIdentificationsMergeHandlerTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/handler/PersonNamesMergeHandlerTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/handler/PersonPhoneEmailMergeHandlerTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/handler/PersonRacesMergeHandlerTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/handler/PersonTableMergeHandlerTest.java
Implement Ethnicity merge logic for patient merge API
1.Ethnicity selected in the Surviving patient are not modified
2.Ethnicity de-selected in the Surviving patient are marked as INACTIVE or LOG_DEL whichever is standard
3.Ethnicity selected in Superseded patients have the person_ethnic_group entry copied to the Surviving patient
4.Ethnicity de-selected in Superseded patients are not modified
https://cdc-nbs.atlassian.net/browse/CND-343
> Implement Ethnicity merge logic for patient merge API

- deduplication/src/test/java/gov/cdc/nbs/deduplication/config/container/MsSqlContainerInitializer.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/config/container/RecordLinkageInitializer.java
1. Adds a static variable in the test container initializer to prevent duplicate containers from being started. 
2. Adds a dependency on the MSSQL container to the Record Linker container
3. Adds exposed port to MSSQL container to allow automatic "ready" check
> Prevent duplicate container startup

- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/pass/AlgorithmMapper.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/pass/PassService.java
- deduplication/src/main/resources/application.yaml
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/pass/AlgorithmMapperTest.java
- deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/pass/PassServiceTest.java
- Added deduplication.algorithm.allowMultipleMatches property with default false
- Replaced hardcoded true with configurable value in AlgorithmContext
https://cdc-nbs.atlassian.net/browse/CND-409
> Make include_multiple_matches configurable

- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonAddressMergeHandler.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonBirthAndSexMergeHandler.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonEthnicityMergeHandler.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonIdentificationsMergeHandler.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonMortalityMergeHandler.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonNamesMergeHandler.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonPhoneEmailMergeHandler.java
- deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonRacesMergeHandler.java
1. Sets `version_ctrl_nbr` when inserting entity_locator_participation.
2. Use HashMap for values of audit since the values can possibly be null. (Prevents NullPointerException with `Map.of...`
- **Related story**: [CND-411](https://cdc-nbs.atlassian.net/browse/CND-411)
[CND-411]: https://cdc-nbs.atlassian.net/browse/CND-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Merge patients - fix failures
