CDCgov/NEDSS-DataIngestion

jwtgenerator/.gitignore, jwtgenerator/Dockerfile, jwtgenerator/README.md, jwtgenerator/build.gradle, jwtgenerator/compose-me.yml, jwtgenerator/pom.xml, jwtgenerator/scripts/jwttester.ksh, jwtgenerator/src/main/java/com/cdceq/jwtgenerator/JwtGenerator.java, jwtgenerator/src/main/java/com/cdceq/jwtgenerator/configs/SwaggerConfig.java, jwtgenerator/src/main/java/com/cdceq/jwtgenerator/controllers/HealthCheckController.java, jwtgenerator/src/main/java/com/cdceq/jwtgenerator/controllers/JwtController.java, jwtgenerator/src/main/java/com/cdceq/jwtgenerator/exceptions/ValidationException.java, jwtgenerator/src/main/java/com/cdceq/jwtgenerator/services/TokenGenerator.java, jwtgenerator/src/main/java/com/cdceq/jwtgenerator/services/TokenInfoHolder.java, jwtgenerator/src/main/java/com/vault/utils/AuthReplyHolder.java, jwtgenerator/src/main/java/com/vault/utils/AuthTokenHolder.java, jwtgenerator/src/main/java/com/vault/utils/SecretsDataHolder.java, jwtgenerator/src/main/java/com/vault/utils/SecretsReplyHolder.java, jwtgenerator/src/main/java/com/vault/utils/VaultValuesResolver.java, jwtgenerator/src/main/resources/application.yaml, ra_20jan2023.txt
=> First version

environments/docker/local/compose-aws-apps.yml, environments/docker/local/compose-mac-apps.yml, environments/docker/local/compose-services.yml, environments/docker/local/initenv, environments/kubernetes/k8s/README.md, environments/kubernetes/k8s/dev/eks/eks-config.yaml, environments/kubernetes/k8s/dev/kafka/deployment/kafka-broker-deployment.yaml, environments/kubernetes/k8s/dev/kafka/deployment/kafka-zoo-deployment.yaml, environments/kubernetes/k8s/dev/kafka/service/ingress-service.yaml, environments/kubernetes/k8s/dev/kafka/service/kafka-broker-service.yaml, environments/kubernetes/k8s/dev/kafka/service/kafka-zoo-service.yaml
First version after consolidations
=> First version after consolidations

jwtgenerator/src/main/java/com/cdceq/jwtgenerator/controllers/JwtController.java
Added a debug statement to double check build process
=> Added a debug statement to double check build process

.github/workflows/Build-phinadapter.yaml
First version of second service in aws ecr
=> First version of second service in aws ecr

report-service/src/main/java/gov/cdc/dataingestion/ServiceApplication.java, report-service/src/main/java/gov/cdc/dataingestion/rawmessage/service/RawELRService.java, report-service/src/main/resources/application.properties
Update topic name for raw message
Update properties to use environment variable
=> updated topic name and added env variable

.gitignore, report-service/build.gradle, report-service/src/main/java/gov/cdc/dataingestion/config/DataSourceConfig.java, report-service/src/main/java/gov/cdc/dataingestion/config/NbsDataSourceConfig.java, report-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java, report-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaProducerService.java, report-service/src/main/java/gov/cdc/dataingestion/nbs/converters/Hl7ToXmlConverter.java, report-service/src/main/java/gov/cdc/dataingestion/nbs/repository/NbsInterfaceRepository.java, report-service/src/main/java/gov/cdc/dataingestion/nbs/repository/model/NbsInterfaceModel.java, report-service/src/main/java/gov/cdc/dataingestion/nbs/services/NbsRepositoryServiceProvider.java, report-service/src/main/resources/application.properties
=> Branch is ready for PR

report-service/src/test/java/gov/cdc/dataingestion/validation/integration/validator/HL7v2ValidatorTests.java
Moved validation unit test to the correct directory
=> move validator unit test to the correct location

.github/workflows/Build-data-ingestion-service.yaml
=> Added CI workflow file

report-service/Dockerfile
=> Added missing build step

.gitignore, report-service/sql-script/elr_dlt.sql, report-service/src/main/java/gov/cdc/dataingestion/deadletter/model/ElrDeadLetterDto.java, report-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java, report-service/src/test/java/gov/cdc/dataingestion/kafka/service/KafkaConsumerServiceTest.java
Fix regex pattern where it wasn't able to process the exception message into the shorter version.
Kavitha checked the result from this branch
=> added fix for dlt exception message

.github/workflows/Build-data-ingestion-service.yaml, .github/workflows/Release-gradle-container.yaml, .github/workflows/sonar.yaml, build.gradle, report-service/src/main/java/gov/cdc/dataingestion/security/config/RsaKeyProperties.java, report-service/src/main/resources/application.yaml
Upgraded github action hook to work with latest CI pipeline.
build.gradle -- plugin added for printversion task, which is being used in the common template file.
sonar.yaml -- To invoke it from Build-data-ingestion-service.yaml
Build-data-ingestion-service.yaml --Updated as Infra team suggested.
Release-gradle-container.yaml -- For manual trigger that is specific to releases.
Refactored the code to pull RSA keys from the environment.
=> Cndit 640 GitHub workflow action

.github/workflows/Build-data-ingestion-service.yaml, .github/workflows/Release-gradle-container.yaml
The following two files have been updated for the CI/CD pipeline.
.github/workflows/Release-gradle-container.yaml
.github/workflows/Build-data-ingestion-service.yaml
=> Added call-update-helm job for CI/CD pipeline

report-service/src/main/java/gov/cdc/dataingestion/registration/controller/RegisterController.java, report-service/src/test/java/gov/cdc/dataingestion/registration/controller/RegisterControllerTest.java
Fixed the bug that created the user with an empty password.
Modified the RegisterController.java and RegisterControllerTest.java.
The fix should be in the 7.1 release.
https://cdc-nbs.atlassian.net/browse/CNDIT-694
=> Added the validation for User Creation

build.gradle, report-service/build.gradle, report-service/src/main/java/gov/cdc/dataingestion/security/config/RsaKeyProperties.java
Testing SonarQ code coverage reports for report-service module.
=> Cndit 699 sonarq fix

report-service/src/main/resources/db/changelog.xml, report-service/src/main/resources/db/report-service-001.sql, report-service/src/main/resources/db/report-service-002.sql
CNDIT-757: Update DI DDL scripts to include the Database creation and selectively create tables only if they are absent.
=> CNDIT-757 : Update the DI Data Definition Language Scripts 

report-service/src/test/java/gov/cdc/dataingestion/rawmessage/controller/ElrReportsControllerTest.java
Failed unit testing because duplicated mock
=> fix failed unit test

report-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java, report-service/src/main/java/gov/cdc/dataingestion/validation/integration/validator/CsvValidator.java, report-service/src/test/java/gov/cdc/dataingestion/kafka/service/KafkaConsumerServiceTest.java
=> fix sonarq complaint

report-service/build.gradle, report-service/src/main/java/gov/cdc/dataingestion/deadletter/model/ElrDeadLetterDto.java
This PR includes the fix for the vulnerabilities that exists in the dependencies. Upgraded couple of dependency version to eliminate the possibility of potential security risk.
- https://cdc-nbs.atlassian.net/browse/CNDIT-755
- Tested building it in my local and the tests ran without any issues.
=> [CNDIT-755] Dependency Vulnerabilities Fix

report-service/src/test/java/gov/cdc/dataingestion/ecr/cdaMapping/CdaMapHelperTest.java, report-service/src/test/java/gov/cdc/dataingestion/ecr/cdaMapping/CdaMapperTest.java, report-service/src/test/java/gov/cdc/dataingestion/ecr/repository/EcrMsgQueryRepositoryTest.java, report-service/src/test/java/gov/cdc/dataingestion/ecr/service/EcrMsgQueryServiceTest.java
More unit testing to pump the overall test
=> CNDIT-717_4

report-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java, report-service/src/main/java/gov/cdc/dataingestion/nbs/converters/Hl7ToRhapsodysXmlConverter.java, report-service/src/main/java/gov/cdc/dataingestion/nbs/services/NbsRepositoryServiceProvider.java, report-service/src/test/java/gov/cdc/dataingestion/kafka/service/KafkaConsumerServiceTest.java, report-service/src/test/java/gov/cdc/dataingestion/nbs/converter/Hl7ToRhapsodysXmlConverterTest.java, report-service/src/test/java/gov/cdc/dataingestion/nbs/service/NbsRepositoryServiceProviderTest.java
Removed hard coded value in XML transformation.
Replaced hard-coded value with actual value from HL7 message
=> Cndit 763 - fix hard coded value

report-service/src/main/java/gov/cdc/dataingestion/rawmessage/controller/ElrReportsController.java, report-service/src/main/java/gov/cdc/dataingestion/share/ControllerExceptionHandler.java, report-service/src/test/java/gov/cdc/dataingestion/rawmessage/ElrReportsControllerTest.java, report-service/src/test/java/gov/cdc/dataingestion/rawmessage/controller/ElrReportsControllerTest.java
Added additional check to prevent user from posting endpoint where required headers are specified but missing value
=> CNDIT-760: prevent user from entering empty header

data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/services/NbsRepositoryServiceProvider.java
- Update NBS_Interaface timestamp col to use Instant Now value from DI
- https://cdc-nbs.atlassian.net/browse/CNDIT-810?atlOrigin=eyJpIjoiZjY4NzlhOGQ1NzMzNGNiYzliYTViMjAzNDVlZjRjMDgiLCJwIjoiaiJ9
=> update to use instant now

data-ingestion-service/src/main/resources/grafana-dashboard/grafana-dashboard.json
- Quick fix for the datasource in the grafana dashboard and removing the tomcat as the metrics are not being pushed to prometheus.
- https://cdc-nbs.atlassian.net/browse/CNDIT-811
=> Grafana Dashboard Fix

build.gradle, cdaschema/build.gradle, data-ingestion-service/build.gradle, data-ingestion-service/src/main/java/gov/cdc/dataingestion/deadletter/controller/ElrDeadLetterController.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/rawmessage/controller/ElrReportsController.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/registration/controller/RegisterController.java, hl7-parser/build.gradle
- We had multiple outdated external dependencies in the `build.gradle` files which was an open door for multiple vulnerabilities.
- This PR address this issue with the upgraded dependencies.
- This will also reduce the vulnerabilities in the EKS container.
- https://cdc-nbs.atlassian.net/browse/CNDIT-781
- Ran `gradle build` on the main package and every test case that we have is passed.
```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│data-ingestion-service:test results: SUCCESS (210 tests, 210 successes, 0 failures, 0 skipped) in 1 minutes, 18.113 seconds                                            │
│Report file: …
```
=> Upgraded external dependencies

data-ingestion-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/services/NbsRepositoryServiceProvider.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/nbs/service/NbsRepositoryServiceProviderTest.java
Added support for retry and dlt for async process
=> added support for retry and dlt in async process

.github/workflows/karate-tests.yaml, data-ingestion-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java
Fixed the issue with the Grafana dashboard where the "Total XML Converted - Success or Failure" metrics displayed the count for all instances instead of the latest one. It appears that the counter did not reset for the new deployment.
https://cdc-nbs.atlassian.net/browse/CNDIT-865
=> Cndit 865 grafana fix

data-ingestion-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaProducerService.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/services/NbsRepositoryServiceProvider.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/kafka/service/KafkaConsumerServiceTest.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/kafka/service/KafkaProducerServiceTest.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/nbs/service/NbsRepositoryServiceProviderTest.java
- Infinite loop occurred after xml transformation logic in some testing scenario
- Built Dlt handler seems to cause this issue
- Added custom Dlt handler specifically for this transformation logic
=> Cndit 898 - Added a fix for infinite loop

data-ingestion-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/services/NbsRepositoryServiceProvider.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/nbs/service/NbsRepositoryServiceProviderTest.java
Support the timestamp format that was sent in from RS integration
=> Update Timestamp parser

data-ingestion-service/src/main/java/gov/cdc/dataingestion/security/config/CustomAuthenticationManagerResolver.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/security/controller/TokenController.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/share/CustomAuthenticationEntryPoint.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/security/controller/TokenControllerTest.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/share/CustomAuthenticationEntryPointTest.java
Changed the code to provide a custom message for the invalid client id and client secrets.
https://cdc-nbs.atlassian.net/browse/CNDIT-915
=> Cndit 915 keycloak validation

.github/workflows/sonar.yaml, data-ingestion-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/kafka/service/KafkaConsumerServiceTest.java, hl7-parser/src/main/java/gov/cdc/dataingestion/hl7/helper/HL7Helper.java, hl7-parser/src/test/java/gov/cdc/dataingestion/hl7/helper/unitTest/FhirConverterTest.java
=> Fix for 'Out of memory error'.

data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/services/NbsRepositoryServiceProvider.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/nbs/service/NbsRepositoryServiceProviderTest.java
Fix for the following formats.
20240305155850.821+0217
20240305155850.821-0217
20240305155850.8211+0217
20240305155850.8211-0217
20240305155850
202403051558
https://cdc-nbs.atlassian.net/browse/CNDIT-1089
=> HL7 parse error for datetime field - fix

data-ingestion-service/src/main/java/gov/cdc/dataingestion/camel/routes/SFTPRouteBuilder.java
Fix for processing the file with the same name that is already processed.
=> SFTP -  Set idempotent true for processing the same file.

README.md, data-ingestion-service/src/main/java/gov/cdc/dataingestion/camel/routes/SFTPRouteBuilder.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/camel/routes/SFTPRouteBuilderTest.java
Sftp move unsupported files to the unprocessed folder.
SFTP camel route name changes.
=> Sftp move unsupported files to the unprocessed folder.

data-ingestion-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaProducerService.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/converters/Hl7ToRhapsodysXmlConverter.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/kafka/service/KafkaConsumerServiceTest.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/kafka/service/KafkaProducerServiceTest.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/nbs/converter/Hl7ToRhapsodysXmlConverterTest.java
- Added check to xml transformation flow to prevent message without date of message in msh to get into the NBS
=> added check for di to look for data of message on msh

data-ingestion-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java
Fix for replacing the error message from HL7 datetime string at MSH-6(0) to HL7 datetime string at MSH-7(0)
=> Fix for error message - HL7 datetime string at MSH-6(0)

data-processing-service/src/main/java/gov/cdc/dataprocessing/constant/EdxPHCRConstants.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/model/container/NotificationProxyContainer.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/model/dto/edx/EdxRuleAlgorothmManagerDto.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/InvestigationNotificationService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/InvestigationService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/PageService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/investigation/AutoInvestigationService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/investigation/DecisionSupportService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/manager/ManagerService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/notification/NotificationService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/other/UidService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/interfaces/IAutoInvestigationService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/interfaces/IInvestigationNotificationService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/interfaces/notification/INotificationService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/interfaces/other/IUidService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/model/action/PageActPatient.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/model/action/PageActPhc.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/utilities/component/PageRepositoryUtil.java
=> Cndit 1279

data-ingestion-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/kafka/service/KafkaConsumerServiceTest.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/kafka/service/KafkaProducerServiceTest.java
Removed the 'CompletableFuture' code from the DI service.
=> Fix for xml parsing on the ELR ingestion in the demo env

data-processing-service/src/main/java/gov/cdc/dataprocessing/constant/elr/EdxELRConstant.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/model/dto/lab_result/EdxLabInformationDto.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/log/EdxLogService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/manager/ManagerAggregationService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/person/PersonService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/utilities/component/observation/ObservationRepositoryUtil.java
Logging for Next of Kin processing is complete.
=> Nok logging

data-processing-service/src/main/java/gov/cdc/dataprocessing/kafka/consumer/KafkaHandleLabConsumer.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/kafka/consumer/KafkaManagerConsumer.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/kafka/consumer/KafkaPublicHealthCaseConsumer.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/repository/nbs/srte/repository/ConditionCodeRepository.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/repository/nbs/srte/repository/LabTestRepository.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/log/EdxLogService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/lookup_data/SrteCodeObsService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/manager/ManagerService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/model/decision_support/DsmLabMatchHelper.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/utilities/component/data_parser/HL7PatientHandler.java
Bug fix for CNDIT 1268 + 1348 + 1308
=> Cndit 1268+1348+1308

.github/workflows/Build-data-ingestion-service.yaml, data-processing-service/Dockerfile, data-processing-service/build.gradle, data-processing-service/src/main/java/gov/cdc/dataprocessing/config/NbsDataSourceConfig.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/config/OdseDataSourceConfig.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/config/SrteDataSourceConfig.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/controller/Controller.java, data-processing-service/src/main/resources/application.yaml
Created Github actions for the data processing deployment.
Added an API endpoint to check the service status.
Updated ENV variables.
=> Created github actions for the data processing deployment

data-processing-service/src/main/java/gov/cdc/dataprocessing/service/model/decision_support/DsmLabMatchHelper.java
=> CNDIT-1342+1372+1267

data-processing-service/src/main/java/gov/cdc/dataprocessing/constant/elr/EdxELRConstant.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/model/dto/lab_result/EdxLabInformationDto.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/log/EdxLogService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/observation/ObservationMatchingService.java
Logging for Observation module complete
=> observation logging

data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/log/EdxLogService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/manager/ManagerService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/organization/OrganizationMatchingService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/utilities/component/public_health_case/PublicHealthCaseRepositoryUtil.java
Implement the logging service for the WDS algorithm.
https://cdc-nbs.atlassian.net/browse/CNDIT-1283
https://cdc-nbs.atlassian.net/browse/CNDIT-1467
=> Cndit 1283 logging wds

data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/person/NokMatchingService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/person/PatientMatchingService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/person/ProviderMatchingService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/person/base/PatientMatchingBaseService.java, data-processing-service/src/test/java/gov/cdc/dataprocessing/service/implementation/person/NokMatchingServiceTest.java, data-processing-service/src/test/java/gov/cdc/dataprocessing/service/implementation/person/PatientMatchingServiceTest.java, data-processing-service/src/test/java/gov/cdc/dataprocessing/service/implementation/person/ProviderMatchingServiceTest.java, data-processing-service/src/test/java/gov/cdc/dataprocessing/service/implementation/person/base/PatientMatchingBaseServiceTest.java
Unit testing has been completed for the files under the 'person' module. The files under person/base need to be done.
=> Cndit 1378 dp unittest person

data-processing-service/src/test/java/gov/cdc/dataprocessing/service/implementation/participation/ParticipationServiceTest.java
=> participation service testing

data-processing-service/src/test/java/gov/cdc/dataprocessing/service/implementation/material/MaterialServiceTest.java
=> Material service testing

data-ingestion-service/src/main/java/gov/cdc/dataingestion/config/DataSourceConfig.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/config/NbsDataSourceConfig.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/config/OdseDataSourceConfig.java, data-ingestion-service/src/main/resources/application.yaml
Clean up the application.yaml file and used one db variable for all the databases.
=> Clean up the application.yaml file and used one db variable for all 

data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/ecr/service/CdaMapper.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/ecr/service/helper/CdaCaseMappingHelper.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/ecr/service/helper/CdaXmlAnswerMappingHelper.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/repository/model/NbsInterfaceModel.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/services/NbsRepositoryServiceProvider.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/rawmessage/controller/EcrReportsController.java
This PR includes the ECR api endpoint update to match the Rhapsody and also few fixes for the CDA mapper with test ECR data.
- https://cdc-nbs.atlassian.net/browse/CNDIT-1638
- https://cdc-nbs.atlassian.net/browse/CNDIT-1566
- Unit tests will be a part of different story which will be done in the upcoming sprints.
=> [CNDIT-1638] ECR endpoint update and CDA mapper fix

data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/ecr/service/EcrMessagePollService.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/rawmessage/controller/EcrReportsController.java
This PR includes the ECR api endpoint update to match the Rhapsody and also new service to poll the data from `NBS_MSGOUTE` tables.
- https://cdc-nbs.atlassian.net/browse/CNDIT-1639
- Unit tests will be a part of different story which will be done in the upcoming sprints.
=> [CNDIT-1639] Poll service added for ECRs and endpoint updated based on Rhapsody route

.github/pull_request_template.md, data-ingestion-service/src/test/java/gov/cdc/dataingestion/ecr/service/EcrMessagePollServiceTest.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/rawmessage/controller/EcrReportsControllerTest.java
PR template added and renamed few unit tests for consistency.
=> Pull request template added

data-ingestion-service/src/main/java/gov/cdc/dataingestion/reportstatus/service/ReportStatusService.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/repository/nbs/odse/repos/log/EdxActivityDetailLogRepository.java, data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/log/EdxLogService.java
=> update edx log so it not adding duplicated data

data-ingestion-service/src/main/resources/application.yaml, data-processing-service/src/main/java/gov/cdc/dataprocessing/controller/Controller.java, data-processing-service/src/main/resources/application.yaml
=> added sub path

data-ingestion-service/src/main/java/gov/cdc/dataingestion/reportstatus/service/ReportStatusService.java
=> encoding payload to base64

data-ingestion-service/src/main/java/gov/cdc/dataingestion/config/OpenAPIConfig.java
=> Update openAPI config to take new sub path into account

data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/log/EdxLogService.java, data-processing-service/src/test/java/gov/cdc/dataprocessing/service/implementation/log/EdxLogServiceTest.java
Bug fix, update log logic in RTI so it can return the correct log
- **Related story**: [CNDE-1580](https://cdc-nbs.atlassian.net/browse/CNDE-1580)
[CNDE-1580]: https://cdc-nbs.atlassian.net/browse/CNDE-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RTI: update log switch logic to return the correct message

data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/uid_generator/UidService.java
Reducing high priority code smell from entire DI repos
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-1565)
=> Final clean on current code smell

data-ingestion-service/src/main/java/gov/cdc/dataingestion/security/config/SecurityConfig.java
Update Security Config
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-1882?atlOrigin=eyJpIjoiOWY3YjRhNDFmNGNiNGQyOWEwMjIzYjdlOTAwMTRlZmEiLCJwIjoiaiJ9)
=> CNDE-1882 update security

data-ingestion-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/services/NbsRepositoryServiceProvider.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/kafka/service/KafkaConsumerServiceTest.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/nbs/service/NbsRepositoryServiceProviderTest.java, data-ingestion-service/src/test/resources/xmlData.txt
This PR is for a bug fix where filler_order_nbr,lab_clia and order_test_code columns are not being populated when a PHDC xml is ingestion in to DI system. 
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-1895)
=> [CNDE-1895] NBS_interface column not populating bug fix

data-processing-service/Dockerfile
=> increase heap memory

data-processing-service/Dockerfile
=> update heap memory usage

data-ingestion-service/src/main/java/gov/cdc/dataingestion/camel/routes/ElrProcessStatusComponent.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/odse/repository/IEdxActivityParentLogRepository.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/odse/repository/model/EdxActivityLog.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/reportstatus/model/EdxLogStatus.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/reportstatus/model/MessageStatus.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/reportstatus/service/ReportStatusService.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/camel/routes/ElrProcessStatusComponentTest.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/reportstatus/service/ReportStatusServiceTest.java
Adding full edx activity to status object
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-1930)
=> added full edx detail object for status

data-processing-service/build.gradle, data-processing-service/src/main/java/gov/cdc/dataprocessing/utilities/component/data_parser/util/CommonLabUtil.java, data-processing-service/src/test/java/gov/cdc/dataprocessing/utilities/component/data_parser/util/CommonLabUtilTest.java
=> using differnt xml package to avoid vulnerability scan

.github/workflows/Build-and-deploy-data-ingestion-and-processing.yaml
Updates workflow to use `paths` only.
=> Update to only use paths

deduplication/src/main/java/gov/cdc/nbs/deduplication/config/DataSourceConfig.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/config/RecordLinkageClientConfig.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/matching/MatchController.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/matching/MatchService.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/matching/exception/MappingException.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/matching/exception/MatchException.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/matching/mapper/LinkRequestMapper.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/matching/model/CreatePersonResponse.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/matching/model/LinkRequest.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/matching/model/LinkResponse.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/matching/model/MatchResponse.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/matching/model/PersonMatchRequest.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/matching/model/RelateRequest.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/seed/step/DeduplicationWriter.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/matching/MatchServiceTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/matching/mapper/LinkRequestMapperTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/seed/step/DeduplicationWriterTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/seed/step/PersonToClusterProcessorTest.java
Adds APIs to deduplication service to support deferring patient deduplication check to Record Linkage service
- **Related story**: [CND-94](https://cdc-nbs.atlassian.net/browse/CND-94)
[CND-94]: https://cdc-nbs.atlassian.net/browse/CND-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add api call for matching

data-processing-service/src/main/java/gov/cdc/dataprocessing/service/implementation/person/matching/DeduplicationClient.java, docs/DataIngestion.postman_collection.json
=> Fixes syntax for ConditonalOnProperty

deduplication/src/main/java/gov/cdc/nbs/deduplication/seed/mapper/MpiPersonMapper.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/seed/mapper/MpiPersonMapperTest.java
Bug Fix for story CND-161
- **Related story**: https://cdc-nbs.atlassian.net/browse/CND-161
=> Fix issue with MpiPersonMapper

containers/db/initialize/restore.d/04-create-deduplication-db.sql, deduplication/src/main/java/gov/cdc/nbs/deduplication/matching/MatchService.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/matching/MatchServiceTest.java
For each match candidate, persists a simplified entry in the deduplication database. This will likely be expanded as more matching info is provided by Record Linkage.
- **Related story**: [CND-164](https://cdc-nbs.atlassian.net/browse/CND-164)
[CND-164]: https://cdc-nbs.atlassian.net/browse/CND-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cnd 164 possible match

data-processing-service/build.gradle
Updates spring boot dependencies of `data-processing-service`
|Dependency | Previous version | New version|
| --- | ---- | ---- | 
|spring-boot-starter-cache | 3.3.4 | 3.4.1|
|spring-boot-starter-data-jpa | 3.3.4 | 3.4.1|
|spring-boot-starter-web | 3.3.4 | 3.4.1|
|spring-boot-starter-oauth2-resource-server | 3.3.4 | 3.4.1|
|spring-boot-starter-logging | 3.3.4 | 3.4.1|
|spring-boot-starter-actuator | 3.3.4 | 3.4.1|
|spring-boot-devtools | 3.3.4 | 3.4.1|
-- None --
=> data-processing-service: Update spring boot version

data-ingestion-service/src/main/java/gov/cdc/dataingestion/rawmessage/service/RawELRService.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/rawmessage/RawELRServiceTest.java
After updating to the newer version of Spring boot, manually setting a UUID for an entity with an auto generated Id, and then persisting it, results in an exception.
- None
=> Fixes issue from manually setting a generated Id

.github/workflows/sonar.yaml, srte-data-service/build.gradle
The srte-data-service uses a test container for its application test. The image to be used was not being passed into the test context.
This should resolve the test failure.
=> Pass through database container image

.github/workflows/Build-and-deploy-deduplication-api.yaml, data-processing-service/src/main/resources/application.yaml, deduplication/Dockerfile, deduplication/build.gradle, deduplication/src/main/resources/application.yaml
Adds a Github workflow to build and store a `deduplication-api` container into ECR.
=> Deduplication container workflow

.github/workflows/Release-container-srte-data-service.yaml
Added workflow to build srte data service image manually
=> add workflow for srte data service

deduplication/src/main/java/gov/cdc/nbs/deduplication/seed/step/SeedWriter.java
Fixes an issue where deleted patient data is seeded into the MPI
NA
=> Check for expanded persons to be active

.github/workflows/Build-and-deploy-deduplication-api.yaml
Fixes a missing space in deduplication workflow. 
Working build after space fix: https://github.com/CDCgov/NEDSS-DataIngestion/actions/runs/13038927625
=> Fix spacing in workflow

data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/ecr/resolver/EcrMsgContainerResolver.java, data-ingestion-service/src/main/resources/application.yaml
Adds a missing annotation.
Adds to comment specifying time is in milliseconds
=> Fix annotation. add MS to timing

deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/model/AlgorithmUpdateRequest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/AlgorithmServiceTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/model/AlgorithmUpdateRequestTest.java
Fixes deduplication container build failure due to failing test.
=> Fix toString and exception test

containers/db/initialize/restore.d/04-create-deduplication-db.sql, deduplication/src/main/java/gov/cdc/nbs/deduplication/constants/QueryConstants.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/controller/MergeGroupController.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/controller/TestController.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/model/MergeGroupResponse.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/model/PossibleMatchGroup.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/service/MergeGroupHandler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/service/PatientRecordService.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/seed/step/SeedWriter.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/controller/MergeGroupControllerTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/controller/TestControllerTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/service/MergeGroupHandlerTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/service/PatientRecordServiceTest.java
Implement API to retrieve patient groups marked for manual de-duplication check
https://cdc-nbs.atlassian.net/browse/CND-204
=>  API to retrieve patient groups 

containers/db/initialize/initialize.sh, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/BatchJobScheduler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/controller/TestController.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/config/container/RecordLinkageInitializer.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/seed/SeedingTest.java
Locks record linker `TestContainer` to `v25.3.0`.
Adds `Qualifier` to a few different spots where a `Job` is autowired in
=> Lock record linker version

.github/workflows/sonar.yaml, data-ingestion-service/Dockerfile, data-ingestion-service/build.gradle
Updated the jar name to contain the release version instead of hardcoded `0.0.1-SNAPSHOT`
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2485)
=> [CNDE-2485] Added config to pull tag from git to update version

data-processing-service/build.gradle, data-processing-service/src/main/resources/application.yaml
=> DP: expose health check

data-ingestion-service/src/main/resources/db/dataingest/tables/di-service-002.sql
=> LIQUIBASAE: update

srte-data-service/build.gradle
=> SRTE: fix srte actuator

deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/config/MapperConfig.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/pass/DibbsService.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/pass/DibbsServiceTest.java
Fixes algorithm enum deserialization for identification types.
- **Related story**: [CND-259](https://cdc-nbs.atlassian.net/browse/CND-259)
[CND-259]: https://cdc-nbs.atlassian.net/browse/CND-259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Set deserialization for enums

.github/workflows/Build-and-deploy-deduplication-api.yaml
Auto deploy updated deduplication-api into INT1.
=> Call update helm for new container

data-ingestion-service/Dockerfile, data-ingestion-service/src/main/resources/db/dataingest/tables/di-service-002.sql, data-processing-service/Dockerfile, data-processing-service/build.gradle
=> DI and DP: vulnerability

data-ingestion-service/src/main/java/gov/cdc/dataingestion/camel/routes/HL7FileProcessComponent.java, data-ingestion-service/src/test/java/gov/cdc/dataingestion/camel/routes/HL7FileProcessComponentTest.java
Fix for integrating the sftp code with a custom mapper.
=> DI sftp custommapper fix

deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/dataelements/model/DataElements.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/pass/AlgorithmMapper.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/algorithm/pass/model/MatchingAttribute.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/dataelements/TestData.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/algorithm/pass/AlgorithmMapperTest.java
Removes telecom as it is not a supported data element.
=> Remove telecom

data-ingestion-service/src/main/java/gov/cdc/dataingestion/camel/routes/ElrProcessStatusComponent.java
Fix on the DI sftp module for elr validation
=> Fix on getting the status from DI sftp module.

data-ingestion-service/src/main/java/gov/cdc/dataingestion/camel/routes/HL7FileProcessComponent.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/camel/routes/SFTPRouteBuilder.java, data-ingestion-service/src/main/resources/application.yaml
=> sftp env params name change.

deduplication/src/main/java/gov/cdc/nbs/deduplication/matching/mapper/LinkRequestMapper.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/seed/JobConfig.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/seed/mapper/MpiPersonMapper.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/seed/model/MpiPerson.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/seed/step/PersonReader.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/seed/step/SeedWriter.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/matching/mapper/LinkRequestMapperTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/seed/SeedingTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/seed/mapper/MpiPersonMapperTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/seed/step/PersonReaderTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/seed/step/SeedWriterTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/sync/service/PersonInsertSyncHandlerTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/sync/service/PersonUpdateSyncHandlerTest.java
Update seeding to resume from the last processed record instead of restarting from the beginning
https://cdc-nbs.atlassian.net/browse/CND-228
=> Update seeding to resume from the last processed record

.github/workflows/Build-and-deploy-data-ingestion-and-processing.yaml, .github/workflows/Build-and-deploy-deduplication-api.yaml, .github/workflows/Release-container-data-ingestion.yaml, .github/workflows/Release-container-data-processing.yaml, .github/workflows/Release-container-srte-data-service.yaml
Update pipeline token handling to restore functionality.
=> Sgz pipeline updates

.github/workflows/Build-and-deploy-data-ingestion-and-processing.yaml, .github/workflows/Build-and-deploy-deduplication-api.yaml
Updates 2 pipeline's token permissions where sonar token is called
=> update sonar token handling

data-ingestion-service/build.gradle, data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/services/NbsRepositoryServiceProvider.java
Kafka version updated.
Fix for formatting ELR specimen collection date time.
=> Updated Kafka version and fix for formatting the elr specimen col date

deduplication/src/main/java/gov/cdc/nbs/deduplication/constants/QueryConstants.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/controller/PatientMergeController.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/service/MergeGroupHandler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/service/MergeGroupService.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/service/PatientRecordService.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/controller/PatientMergeControllerTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/service/MergeGroupHandlerTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/service/MergeGroupServiceTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/service/PatientRecordServiceTest.java
The Patient merge landing page allows the user to export the list of matches requiring review. A new API needs to be created to allow export of the list as a CSV.
The api link in the below image has been updated to `http://localhost:8083/nbs/api/deduplication/merge/matches/requiring-review/export/csv`
- **Related story**: [CND-294](https://cdc-nbs.atlassian.net/browse/CND-294?atlOrigin=eyJpIjoiNTg4NGNjZDY5YzEzNDNhY2IwZTcyZjU2YzVkZjk3NDciLCJwIjoiaiJ9)
[CND-294]: https://cdc-nbs.atlassian.net/browse/CND-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CND 294: Export CSV for Matches Requiring Review

deduplication/src/main/java/gov/cdc/nbs/deduplication/constants/QueryConstants.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/mapper/PersonMergeDataMapper.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/model/PersonMergeData.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/controller/PatientMergeControllerTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/mapper/PersonMergeDataMapperTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/service/MergeGroupHandlerTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/service/PatientRecordServiceTest.java
Add an API to retrieve merge candidate extra data by patient ID.
https://cdc-nbs.atlassian.net/browse/CND-280
https://cdc-nbs.atlassian.net/browse/CND-281
=> Add an API to retrieve merge candidate extra data by patient ID.

deduplication/src/main/java/gov/cdc/nbs/deduplication/config/AsyncJobLauncherConfig.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/BatchJobConfig.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/BatchJobScheduler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/controller/BatchController.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/step/DuplicatesProcessor.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/duplicates/step/UnprocessedPersonReader.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/seed/SeedController.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/seed/SeedJobConfig.java, deduplication/src/main/resources/application.yaml, deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/BatchJobSchedulerTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/controller/TestControllerTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/step/DuplicatesProcessorTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/duplicates/step/UnprocessedPersonReaderTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/seed/SeedJobConfigTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/seed/SeedingTest.java, deduplication/src/test/resources/application-test.yml
1. Limits the execution of batch processing to the configured limits
2. Switches to an Async job launcher so API requests do not hang until completion of process
- **Related story**: [CND-298](https://cdc-nbs.atlassian.net/browse/CND-298)
[CND-298]: https://cdc-nbs.atlassian.net/browse/CND-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cnd 298 batch limit

data-ingestion-service/src/main/java/gov/cdc/dataingestion/camel/routes/SFTPRouteBuilder.java
Resolved the issue on DI sftp that occurs when a file name contains dots.
=> Resolved the issue on DI sftp that occurs when a file name contains dots.

data-ingestion-service/build.gradle, data-processing-service/build.gradle, deduplication/build.gradle, srte-data-service/build.gradle
Upgraded spring boot version to 3.4.5 to fix the CVE issues
=> CVE fix. upgraded spring boot version to 3.4.5

deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/MatchesRequiringReviewResolver.java
1. Fixes the count query for patient merge landing page
2. Removes duplicate column name from query
- **Related story**: [CND-302](https://cdc-nbs.atlassian.net/browse/CND-302)
[CND-302]: https://cdc-nbs.atlassian.net/browse/CND-302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix count query

deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/PatientMergeController.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/PdfBuilder.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/PatientMergeControllerTest.java
On the Merge Review Landing Page, make the following updates for the PDF/CSV exports:
1. When you print to a PDF or CSV, the column names should match the column name on screen (created date vs. date created, matching records vs. number of matching records, etc)
2. If you sort the table by a certain column and then you go to print a PDF or download a CSV, that sorting should persist. 
- **Related story**: [CND-318](https://cdc-nbs.atlassian.net/browse/CND-318?atlOrigin=eyJpIjoiNTkxOTlmYWE2NjE4NGM0ZThjYzRiODA0NTkzODU0NmEiLCJwIjoiaiJ9)
[CND-318]: https://cdc-nbs.atlassian.net/browse/CND-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adjust endpoints for pdf/csv export

deduplication/src/main/java/gov/cdc/nbs/deduplication/batch/model/GroupNoMergeRequest.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/constants/QueryConstants.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/MergeGroupHandler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/PatientMergeController.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/batch/service/MergeGroupHandlerTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/PatientMergeControllerTest.java
Add API to remove (keep separate) patients from merge list
https://cdc-nbs.atlassian.net/browse/CND-305
=> Add API to remove (keep separate) patients from merge list

deduplication/src/main/java/gov/cdc/nbs/deduplication/batch/mapper/PersonMergeDataMapper.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/batch/model/PersonMergeData.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/constants/QueryConstants.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/MergeGroupHandler.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/batch/mapper/PersonMergeDataMapperTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/batch/service/MergeGroupHandlerTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/batch/service/PatientRecordServiceTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/PatientMergeControllerTest.java
1. Adds person_uid to patient details response
2. Nests admin comments into record
3. Updates comment date to be timestamp so that it is parsable by existing UI methods
- **Related story**: [CND-279](https://cdc-nbs.atlassian.net/browse/CND-279)
[CND-279]: https://cdc-nbs.atlassian.net/browse/CND-279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Support UI admin comments section

containers/db/initialize/restore.d/04-create-deduplication-db.sql, deduplication/src/main/java/gov/cdc/nbs/deduplication/batch/step/MatchCandidateWriter.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/constants/QueryConstants.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/MergeGroupHandler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/MergePatientHandler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/sync/service/PersonInsertSyncHandler.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/batch/service/MergeGroupHandlerTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/batch/step/MatchCandidateWriterTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/sync/service/PersonInsertSyncHandlerTest.java
- Renamed match_candidates to matches_requiring_review
- Removed potential_match_person_uid and is_merge fields
- Created new match_candidates join table with match_id FK,person_uid, and is_merge
No Jira ticket yet — will update this PR with the link when available.
=> normalize match candidate structure with new join table

data-ingestion-service/build.gradle
=> CVE: update tomcat

data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/ecr/service/CdaMapper.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/ecr/service/helper/CdaCaseMappingHelper.java, data-ingestion-service/src/main/java/gov/cdc/dataingestion/nbs/ecr/service/helper/CdaMapHelper.java
This PR includes a bug fix for the eICR 1.1 ingestion reported by MT. Fix is tested in DTS1 with de-anonymized data from MT
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2914)
=> [CNDE-2847] eICR NOT_MAPPED bug fix

data-processing-service/src/main/resources/application.yaml
=> enabled web app

data-ingestion-service/build.gradle
=> Resolved CVE

deduplication/build.gradle, deduplication/src/main/java/gov/cdc/nbs/deduplication/config/auth/IgnoredPaths.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/config/auth/oidc/OidcRestClientConfig.java
Updates Deduplication-api to Spring boot 3.5.3
=> Upgrade to spring boot 3.5.3

data-ingestion-service/src/main/java/gov/cdc/dataingestion/share/helper/OBRSplitter.java
Fix the obr ID in the multi obr ELR before splitting.
=> DI obr splitter fix

deduplication/src/main/java/gov/cdc/nbs/deduplication/config/DataSourceConfig.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/constants/QueryConstants.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/MergeService.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/AdminCommentMergeHandler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonAddressMergeHandler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonBirthAndSexMergeHandler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonEthnicityMergeHandler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonGeneralInfoMergeHandler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonIdentificationsMergeHandler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonMortalityMergeHandler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonNamesMergeHandler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonPhoneEmailMergeHandler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonRacesMergeHandler.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/handler/PersonTableMergeHandler.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/MergeServiceTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/handler/PersonTableMergeHandlerTest.java
1. Force use of NBS Datasource Transaction manager during patient merge
2. Defer Deduplication database update until patient merge is complete
3. Prevents sorting of handlers on every merge
N/A
=> Merge - Transaction rollback

deduplication/src/main/java/gov/cdc/nbs/deduplication/seed/step/MpiReader.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/seed/step/MpiReaderTest.java, deduplication/src/test/resources/application-test.yml
Fixes bug in seed query where query would fail on multiple pages
N/A
=> Fix seed query for multiple pages

deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/PatientMergeController.java
Updates default merge sort to match what UI sets as default sort
N/A
=> Change default sort to identification date

deduplication/src/main/java/gov/cdc/nbs/deduplication/auth/authentication/PermissionResolver.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/batch/mapper/PersonMergeDataMapper.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/batch/model/PersonMergeData.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/batch/service/PatientRecordService.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/constants/QueryConstants.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/auth/authentication/PermissionResolverTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/batch/mapper/PersonMergeDataMapperTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/batch/service/PatientRecordServiceTest.java
1. Restrict Investigations returned based on user permission set
2. Restrict HIV case Id based on user permission
3. Apply ordering to Investigations (newest first, nulls last)
- **Related story**: [CND-388](https://cdc-nbs.atlassian.net/browse/CND-388)
[CND-388]: https://cdc-nbs.atlassian.net/browse/CND-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Merge - Investigation/HIV Permission issues

deduplication/src/main/java/gov/cdc/nbs/deduplication/constants/QueryConstants.java
Sort repeating block data newest first
- **Related story**: [CND-389](https://cdc-nbs.atlassian.net/browse/CND-389)
[CND-389]: https://cdc-nbs.atlassian.net/browse/CND-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add sort to merge review query

.github/workflows/Build-and-deploy-data-ingestion-and-processing.yaml, .github/workflows/Build-and-deploy-data-ingestion.yaml, .github/workflows/Build-and-deploy-data-processing.yaml, .github/workflows/Production-release-image.yaml, .github/workflows/karate-tests.yaml
=> Update Github action

data-ingestion-service/src/main/resources/application.yaml
=> reenabled prometheus endpoint

data-ingestion-service/src/main/java/gov/cdc/dataingestion/kafka/integration/service/KafkaConsumerService.java
=> Update - add raw id as comment in xml payload

data-processing-service/build.gradle
=> DP - fixed CVE

deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/MatchesRequiringReviewResolver.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/PatientMergeController.java, deduplication/src/main/java/gov/cdc/nbs/deduplication/merge/model/PatientMergeQueueStatus.java, deduplication/src/main/resources/application.yaml, deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/MatchesRequiringReviewResolverTest.java, deduplication/src/test/java/gov/cdc/nbs/deduplication/merge/PatientMergeControllerTest.java
As a user with Merge permission, I can see an indicator and navigate to the potential merge queue if the patient is there.
- **Related story**: [CND-371](https://cdc-nbs.atlassian.net/browse/CND-371?atlOrigin=eyJpIjoiODI2MDRiZDdhNmJlNGUwYzlhMDA4NTE2MjNlZWZiNGYiLCJwIjoiaiJ9)
[CND-371]: https://cdc-nbs.atlassian.net/browse/CND-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> API: Merge Queue

data-ingestion-service/src/main/java/gov/cdc/dataingestion/security/config/SecurityConfig.java
Prometheus endpoint fix for Data Ingestion dev environment.
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-3108)
=> [CNDE-3108] Updated prometheus endpoint
